version: '3.5'

services:
  postgres:
    image: postgres:9.6.18-alpine
    volumes:
    - ./volumes/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "user_info"
      POSTGRES_PASSWORD: "password"
    ports:
    - 5432:5432

